Repository Ankit-11525/e-commerce_redstore.github.io, pull requests merged in 2022-10, with the labels that each got.

#7 Updated copyright year to use js.
  account.html
  allproducts.html
  cart.html
  index.html
  productdetail.html
Labels: hacktoberfest

#8 Fixed nav-links' alignment
  style.css
Labels: hacktoberfest

#68 Added Image Animation and CSS Edits.
  index.html
  style.css
Labels: enhancement, hacktoberfest, hacktoberfest-accepted, hacktoberfest-Updated

#87 social media icon fixes
  index.html
  style.css
Labels: bug, good first issue, hacktoberfest, hacktoberfest-accepted, hacktoberfest-Updated

#90 Added toggle button for changing theme.
  account.html
  allproducts.html
  cart.html
  index.html
  productdetail.html
  style.css
Labels: enhancement, hacktoberfest, hacktoberfest-accepted, hacktoberfest-Updated
